CREATE TABLE signature_credentials (
    id VARCHAR(36) NOT NULL,
    clinic_id VARCHAR(36) NOT NULL,
    professional_id VARCHAR(36) NOT NULL,
    mode VARCHAR(30) NOT NULL,
    provider_key VARCHAR(80),
    display_name VARCHAR(160) NOT NULL,
    subject_name VARCHAR(500) NOT NULL,
    issuer_name VARCHAR(500),
    serial_number VARCHAR(120) NOT NULL,
    fingerprint_sha256 CHAR(64) NOT NULL,
    valid_from DATETIME(6) NOT NULL,
    valid_until DATETIME(6) NOT NULL,
    remote_credential_id VARCHAR(240),
    remote_secret_kind VARCHAR(20),
    encrypted_material MEDIUMBLOB NOT NULL,
    encryption_iv VARBINARY(12) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    ownership_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_user_id VARCHAR(36) NOT NULL,
    last_used_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_signature_credentials_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_signature_credentials_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT fk_signature_credentials_user FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT uk_signature_credentials_fingerprint UNIQUE (clinic_id, professional_id, fingerprint_sha256),
    INDEX ix_signature_credentials_owner (clinic_id, professional_id, active)
) ENGINE=InnoDB;

CREATE TABLE document_signatures (
    id VARCHAR(36) NOT NULL,
    clinic_id VARCHAR(36) NOT NULL,
    document_id VARCHAR(36) NOT NULL,
    credential_id VARCHAR(36) NOT NULL,
    mode VARCHAR(30) NOT NULL,
    provider_key VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    signer_subject VARCHAR(500),
    certificate_serial VARCHAR(120),
    certificate_fingerprint CHAR(64),
    signed_by_user_id VARCHAR(36) NOT NULL,
    requested_at DATETIME(6) NOT NULL,
    signed_at DATETIME(6),
    signed_pdf_path VARCHAR(500),
    signed_pdf_hash CHAR(64),
    failure_message VARCHAR(1000),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_signatures_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_document_signatures_document FOREIGN KEY (document_id) REFERENCES clinical_documents (id),
    CONSTRAINT fk_document_signatures_credential FOREIGN KEY (credential_id) REFERENCES signature_credentials (id),
    CONSTRAINT fk_document_signatures_user FOREIGN KEY (signed_by_user_id) REFERENCES app_users (id),
    CONSTRAINT uk_document_signatures_document UNIQUE (document_id),
    INDEX ix_document_signatures_clinic_status (clinic_id, status, requested_at)
) ENGINE=InnoDB;

ALTER TABLE clinical_documents
    ADD COLUMN signed_at DATETIME(6) NULL AFTER finalized_at,
    ADD COLUMN signed_pdf_hash CHAR(64) NULL AFTER document_hash;
